!
! DESCRIP.MMS - MMS description file for stringio
!
.INCLUDE COM$:EXTLIB_COMMON.MMS

EXE$:STRINGIO.EXE : -
	OBJ$:STRINGIO.OBJ, -
	EXE$:RUBYSHR.EXE
    $(LINK)$(LINKDEBFLAGS)$(LINKSHRFLAGS) -
	OBJ$:STRINGIO.OBJ, -
	EXTSRC$:[STRINGIO]STRINGIO.OPT/OPTION, -
	SRC$:EXTLIB.OPT/OPTION, OBJ$:VERSION.OPT/OPTION

OBJ$:STRINGIO.OBJ : EXTSRC$:[STRINGIO]STRINGIO.C

!
! move to the target directory
!
BLDLIB : 
  COPY EXE$:STRINGIO.EXE $(TARGET)STRINGIO.EXE 

