!
! DESCRIP.MMS - MMS description file for blockio
!
.INCLUDE COM$:EXTLIB_COMMON.MMS

EXE$:LCKLIB.EXE : -
	OBJ$:LCKLIB.OBJ, -
	EXE$:RUBYSHR.EXE
    $(LINK)$(LINKDEBFLAGS)$(LINKSHRFLAGS) -
	OBJ$:LCKLIB.OBJ, -
	EXTSRC$:[LCKLIB]LCKLIB.OPT/OPTION, -
	SRC$:EXTLIB.OPT/OPTION, OBJ$:VERSION.OPT/OPTION

OBJ$:LCKLIB.OBJ : EXTSRC$:[LCKLIB]LCKLIB.C

!
! move to the target directory
!
BLDLIB : 
  COPY EXE$:LCKLIB.EXE $(TARGET)LCKLIB.EXE 

