$ COPY SRC$:IO.C TMPSRC$:'F$PARSE("SRC$:IO.C",,,"NAME")'
$ CC/OBJECT=OBJ$:IO.OBJ/LIST=LIS$:.LIS/STANDARD=RELAXED_ANSI89 -
   /PREFIX=EXCEPT=(vsnprintf,snprintf,gai_strerror) -
   /DEFINE=(__FAST_SETJMP)/NAME=(UPPERCASE,SHORTENED) -
   /REPOSITORY=OBJ$/ACCEPT=GCCINLINE/SHOW=ALL -
   /FLOATING=IEEE/IEEE_MODE=INEXACT/WARNINGS=(INFORMATIONAL=ALL) -
   TMPSRC$:'F$PARSE("SRC$:IO.C",,,"NAME")'
