!
! DESCRIP.MMS - MMS description file for fcntl
!
.INCLUDE COM$:EXTLIB_COMMON.MMS

EXE$:STRSCAN.EXE : -
	OBJ$:STRSCAN.OBJ, -
	EXE$:RUBYSHR.EXE
    $(LINK)$(LINKDEBFLAGS)$(LINKSHRFLAGS) -
	OBJ$:STRSCAN.OBJ, -
	EXTSRC$:[STRSCAN]STRSCAN.OPT/OPTION, -
	SRC$:EXTLIB.OPT/OPTION, OBJ$:VERSION.OPT/OPTION

OBJ$:STRSCAN.OBJ : EXTSRC$:[STRSCAN]STRSCAN.C

!
! move to the target directory
!
BLDLIB : 
  COPY EXE$:STRSCAN.EXE $(TARGET)STRSCAN.EXE 

