!
! DESCRIP.MMS - MMS description file for fcntl
!
.INCLUDE COM$:EXTLIB_COMMON.MMS

EXE$:FCNTL.EXE : -
	OBJ$:FCNTL.OBJ, -
	EXE$:RUBYSHR.EXE
    $(LINK)$(LINKDEBFLAGS)$(LINKSHRFLAGS) -
	OBJ$:FCNTL.OBJ, -
	EXTSRC$:[FCNTL]FCNTL.OPT/OPTION, -
	SRC$:EXTLIB.OPT/OPTION, OBJ$:VERSION.OPT/OPTION

OBJ$:FCNTL.OBJ : EXTSRC$:[FCNTL]FCNTL.C

!
! move to the target directory
!
BLDLIB : 
  COPY EXE$:FCNTL.EXE $(TARGET)FCNTL.EXE 

